global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postfix'
    scrape_interval: 5s
    static_configs:
      - targets: ['mailserver:9154']

  - job_name: 'dovecot'
    scrape_interval: 5s
    static_configs:
      - targets: ['mailserver:9900']
